project_id = "hzxenhkmawctxzdjvnyw"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.check-admin-session]
verify_jwt = false

[functions.notify-whatsapp-registration]
verify_jwt = false

[functions.send-invoice-whatsapp]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false
